### ISSUE TITLE
nightly_builds.yml - provisioningProfile parameter

### ISSUE THREAD

**Issue by DanielsonZI** [damienaicheh/ShrinkYAMLSample#1]
Hello,

In file 'nightly_builds.yml' there are parameters 'provisioningProfile' for env 'staging' and 'production' that are probably incorrectly labeled, because such parameters are not used

**Comment by damienaicheh** [comment]
Thanks for the PR, I also updated the article! I did a mistake while trying to find some not specific words. Thanks again for your feedbacks :)
